Entity/Topic.php
<?php

/*
 * This file is part of the CCDNForum ForumBundle
 *
 * (c) CCDN (c) CodeConsortium <http://www.codeconsortium.com/>
 *
 * Available on github <http://www.github.com/codeconsortium/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CCDNForum\ForumBundle\Entity;

use CCDNForum\ForumBundle\Entity\Model\Topic as AbstractTopic;

/**
 *
 * @category CCDNForum
 * @package  ForumBundle
 *
 * @author   Reece Fowell <reece@codeconsortium.com>
 * @license  http://opensource.org/licenses/MIT MIT
 * @version  Release: 2.0
 * @link     https://github.com/codeconsortium/CCDNForumForumBundle
 *
 */
class Topic extends AbstractTopic
{
    /**
     *
     * @var integer $id
     */
    protected $id;

    /**
     *
     * @var string $title
     */
    protected $title;

    /**
     *
     * @var integer $cachedViewCount
     */
    protected $cachedViewCount = 0;

    /**
     *
     * @var integer $cachedReplyCount
     */
    protected $cachedReplyCount = 0;

    /**
     *
     * @var Boolean $isClosed
     */
    protected $isClosed = false;

    /**
     *
     * @var \DateTime $closedDate
     */
    protected $closedDate;

    /**
     *
     * @var Boolean $isDeleted
     */
    protected $isDeleted = false;

    /**
     *
     * @var \DateTime $deletedDate
     */
    protected $deletedDate;

    /**
     *
     * @var \DateTime $stickiedDate
     */
    protected $stickiedDate;

    /**
     *
     *  @var Boolean $isSticky
     */
    protected $isSticky = false;

    /**
     *
     * @access public
     */
    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set title
     *
     * @param  string $title
     * @return Topic
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get cachedViewCount
     *
     * @return integer
     */
    public function getCachedViewCount()
    {
        return $this->cachedViewCount;
    }

    /**
     * Set cachedViewCount
     *
     * @param  integer $cachedViewCount
     * @return Topic
     */
    public function setCachedViewCount($cachedViewCount)
    {
        $this->cachedViewCount = $cachedViewCount;

        return $this;
    }

    /**
     * Get cachedReplyCount
     *
     * @return integer
     */
    public function getCachedReplyCount()
    {
        return $this->cachedReplyCount;
    }

    /**
     * Set cachedReplyCount
     *
     * @param  integer $cachedReplyCount
     * @return Topic
     */
    public function setCachedReplyCount($cachedReplyCount)
    {
        $this->cachedReplyCount = $cachedReplyCount;

        return $this;
    }

    /**
     * Get isClosed
     *
     * @return boolean
     */
    public function isClosed()
    {
        return $this->isClosed;
    }

    /**
     * Set isClosed
     *
     * @param  boolean $isClosed
     * @return Topic
     */
    public function setClosed($isClosed)
    {
        $this->isClosed = $isClosed;

        return $this;
    }

    /**
     * Get closedDate
     *
     * @return \datetime
     */
    public function getClosedDate()
    {
        return $this->closedDate;
    }

    /**
     * Set closedDate
     *
     * @param  \datetime $closedDate
     * @return Topic
     */
    public function setClosedDate($closedDate)
    {
        $this->closedDate = $closedDate;

        return $this;
    }

    /**
     * Get isDeleted
     *
     * @return boolean
     */
    public function isDeleted()
    {
        return $this->isDeleted;
    }

    /**
     * Set isDeleted
     *
     * @param  boolean $isDeleted
     * @return Topic
     */
    public function setDeleted($isDeleted)
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }

    /**
     * Get deletedDate
     *
     * @return \datetime
     */
    public function getDeletedDate()
    {
        return $this->deletedDate;
    }

    /**
     * Set deletedDate
     *
     * @param  \datetime $deletedDate
     * @return Topic
     */
    public function setDeletedDate($deletedDate)
    {
        $this->deletedDate = $deletedDate;

        return $this;
    }

    /**
     * Get isSticky
     *
     * @return boolean
     */
    public function isSticky()
    {
        return $this->isSticky;
    }

    /**
     * Set isSticky
     *
     * @param  boolean $isSticky
     * @return Topic
     */
    public function setSticky($isSticky)
    {
        $this->isSticky = $isSticky;

        return $this;
    }

    /**
     * Get stickiedDate
     *
     * @return \datetime
     */
    public function getStickiedDate()
    {
        return $this->stickiedDate;
    }

    /**
     * Set stickiedDate
     *
     * @param  \datetime $stickiedDate
     * @return Topic
     */
    public function setStickiedDate($stickiedDate)
    {
        $this->stickiedDate = $stickiedDate;

        return $this;
    }
}

Form/Type/User/Topic/TopicUpdateFormType.php
<?php

/*
 * This file is part of the CCDNForum ForumBundle
 *
 * (c) CCDN (c) CodeConsortium <http://www.codeconsortium.com/>
 *
 * Available on github <http://www.github.com/codeconsortium/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CCDNForum\ForumBundle\Form\Type\User\Topic;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 *
 * @category CCDNForum
 * @package  ForumBundle
 *
 * @author   Reece Fowell <reece@codeconsortium.com>
 * @license  http://opensource.org/licenses/MIT MIT
 * @version  Release: 2.0
 * @link     https://github.com/codeconsortium/CCDNForumForumBundle
 *
 */
class TopicUpdateFormType extends AbstractType
{
    /**
     *
     * @access protected
     * @var string $topicClass
     */
    protected $topicClass;

    /**
     *
     * @access public
     * @param string $topicClass
     */
    public function __construct($topicClass)
    {
        $this->topicClass = $topicClass;
    }

    /**
     *
     * @access public
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null,
                array(
                    'label'              => 'topic.title-label',
                    'translation_domain' => 'CCDNForumForumBundle'
                )
            )
        ;
    }

    /**
     *
     * @access public
     * @param \Symfony\Component\OptionsResolver\OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class'         => $this->topicClass,
            'csrf_protection'    => true,
            'csrf_field_name'    => '_token',
            // a unique key to help generate the secret token
            'intention'          => 'forum_topic_update_item',
            'validation_groups'  => array('forum_topic_update', 'forum_post_update'),
        ));
    }

    /**
     *
     * @access public
     * @return string
     */
    public function getName()
    {
        return 'Topic';
    }
}

Controller/BaseController.php
<?php

/*
 * This file is part of the CCDNForum ForumBundle
 *
 * (c) CCDN (c) CodeConsortium <http://www.codeconsortium.com/>
 *
 * Available on github <http://www.github.com/codeconsortium/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CCDNForum\ForumBundle\Controller;

use Symfony\Component\DependencyInjection\ContainerAware;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\EventDispatcher\Event;

use CCDNForum\ForumBundle\Entity\Topic;
use CCDNForum\ForumBundle\Entity\Post;

/**
 *
 * @category CCDNForum
 * @package  ForumBundle
 *
 * @author   Reece Fowell <reece@codeconsortium.com>
 * @license  http://opensource.org/licenses/MIT MIT
 * @version  Release: 2.0
 * @link     https://github.com/codeconsortium/CCDNForumForumBundle
 *
 */
class BaseController extends ContainerAware
{
    /**
     *
     * @var \Symfony\Bundle\FrameworkBundle\Routing\Router $router
     */
    private $router;

    /**
     *
     * @var \Symfony\Bundle\TwigBundle\Debug\TimedTwigEngine $templating
     */
    private $templating;

    /**
     *
     * @var \Symfony\Component\HttpFoundation\Request $request
     */
    protected $request;

    /**
     *
     * @var \Symfony\Component\EventDispatcher\EventDispatcherInterface  $dispatcher;
     */
    protected $dispatcher;

    /**
     *
     * @var \Symfony\Component\Security\Core\SecurityContext $securityContext
     */
    private $securityContext;

    /**
     *
     * @var \CCDNForum\ForumBundle\Component\Security\Authorizer $authorizer;
     */
    private $authorizer;

    /**
     *
     * @var \CCDNForum\ForumBundle\Model\FrontModel\ForumModel $forumModel
     */
    private $forumModel;

    /**
     *
     * @var \CCDNForum\ForumBundle\Model\FrontModel\CategoryModel $categoryModel
     */
    private $categoryModel;

    /**
     *
     * @var \CCDNForum\ForumBundle\Model\FrontModel\BoardModel $boardModel
     */
    private $boardModel;

    /**
     *
     * @var \CCDNForum\ForumBundle\Model\FrontModel\TopicModel $topicModel
     */
    private $topicModel;

    /**
     *
     * @var \CCDNForum\ForumBundle\Model\FrontModel\PostModel $postModel
     */
    private $postModel;

    /**
     *
     * @var \CCDNForum\ForumBundle\Model\FrontModel\RegistryModel $registryModel
     */
    private $registryModel;

    /**
     *
     * @var \CCDNForum\ForumBundle\Model\FrontModel\SubscriptionModel $subscriptionModel
     */
    private $subscriptionModel;

    /**
     *
     * @access protected
     * @return \Symfony\Bundle\FrameworkBundle\Routing\Router
     */
    protected function getRouter()
    {
        if (null == $this->router) {
            $this->router = $this->container->get('router');
        }

        return $this->router;
    }

    /**
     *
     * @access protected
     * @param  string $route
     * @param  Array  $params
     * @return string
     */
    protected function path($route, $params = array())
    {
        return $this->getRouter()->generate($route, $params);
    }

    /**
     *
     * @access protected
     * @return \Symfony\Bundle\TwigBundle\Debug\TimedTwigEngine
     */
    protected function getTemplating()
    {
        if (null == $this->templating) {
            $this->templating = $this->container->get('templating');
        }

        return $this->templating;
    }

    /**
     *
     * @access protected
     * @return \Symfony\Component\HttpFoundation\Request
     */
    protected function getRequest()
    {
        if (null == $this->request) {
            $this->request = $this->container->get('request');
        }

        return $this->request;
    }

    /**
     *
     * @access protected
     * @param  string $prefix
     * @return Array
     */
    protected function getCheckedItemIds($prefix = 'check_', $enforceNumericType = true)
    {
        $request = $this->getRequest();

        $sanitarisedIds = array();

        if ($request->request->has($prefix)) {
            $itemIds = $request->request->get($prefix);

            foreach ($itemIds as $id => $val) {
                if ($enforceNumericType == true) {
                    if (! is_numeric($id)) {
                        continue;
                    }
                }

                $sanitarisedIds[] = $id;
            }
        }

        return $sanitarisedIds;
    }

    /**
     *
     * @access protected
     * @param  string $template
     * @param  Array  $params
     * @param  string $engine
     * @return string
     */
    protected function renderResponse($template, $params = array(), $engine = null)
    {
        return $this->getTemplating()->renderResponse($template . ($engine ?: $this->getEngine()), $params);
    }

    /**
     *
     * @access protected
     * @param  string                                             $url
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectResponse($url)
    {
        return new RedirectResponse($url);
    }

    /**
     *
     * @access protected
     * @param  string                                             $forumName
     * @param  \CCDNForum\ForumBundle\Entity\Topic                $topic
     * @param  \CCDNForum\ForumBundle\Entity\Post                 $post
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectResponseForTopicOnPageFromPost($forumName, Topic $topic, Post $post)
    {
        //$page = $this->getTopicModel()->getPageForPostOnTopic($topic, $topic->getLastPost()); // Page of the last post.
        $response = $this->redirectResponse($this->path('ccdn_forum_user_topic_show', array(
            'forumName' => $forumName,
            'topicId' => $topic->getId(),
            /*'page' => $page*/
        )) /* . '#' . $topic->getLastPost()->getId()*/);

        return $response;
    }

    /**
     *
     * @access protected
     * @return string
     */
    protected function getEngine()
    {
        return $this->container->getParameter('ccdn_forum_forum.template.engine');
    }

    /**
     *
     * @access protected
     * @return \Symfony\Component\Security\Core\SecurityContext
     */
    protected function getSecurityContext()
    {
        if (null == $this->securityContext) {
            $this->securityContext = $this->container->get('security.context');
        }

        return $this->securityContext;
    }

    /**
     *
     * @access protected
     * @return \Symfony\Component\Security\Core\User\UserInterface
     */
    protected function getUser()
    {
        return $this->getSecurityContext()->getToken()->getUser();
    }

    /**
     *
     * @access protected
     * @param  string $role
     * @return bool
     */
    protected function isGranted($role)
    {
        if (! $this->getSecurityContext()->isGranted($role)) {
            return false;
        }

        return true;
    }

    /**
     *
     * @access protected
     * @param  string                                                           $role|boolean $role
     * @throws \Symfony\Component\Security\Core\Exception\AccessDeniedException
     */
    protected function isAuthorised($role)
    {
        if (is_bool($role)) {
            if ($role == false) {
                throw new AccessDeniedException('You do not have permission to use this resource.');
            }

            return true;
        }

        if (! $this->isGranted($role)) {
            throw new AccessDeniedException('You do not have permission to use this resource.');
        }

        return true;
    }

    /**
     *
     * @access protected
     * @param  \Object                                                      $item
     * @param  string                                                       $message
     * @return bool
     * @throws Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     */
    protected function isFound($item, $message = null)
    {
        if (null == $item) {
            throw new NotFoundHttpException($message ?: 'Page you are looking for could not be found!');
        }

        return true;
    }

    protected function getQuery($query, $default)
    {
        return $this->getRequest()->query->get($query, $default);
    }

    protected function dispatch($name, Event $event)
    {
        if (! $this->dispatcher) {
            $this->dispatcher = $this->container->get('event_dispatcher');
        }

        $this->dispatcher->dispatch($name, $event);
    }

    /**
     *
     * @access protected
     * @return \CCDNForum\ForumBundle\Component\Security\Authorizer
     */
    protected function getAuthorizer()
    {
        if (null == $this->authorizer) {
            $this->authorizer = $this->container->get('ccdn_forum_forum.component.security.authorizer');
        }

        return $this->authorizer;
    }

    /**
     *
     * @access protected
     * @return \CCDNForum\ForumBundle\Model\FrontModel\ForumModel
     */
    protected function getForumModel()
    {
        if (null == $this->forumModel) {
            $this->forumModel = $this->container->get('ccdn_forum_forum.model.forum');
        }

        return $this->forumModel;
    }

    /**
     *
     * @access protected
     * @return \CCDNForum\ForumBundle\Model\FrontModel\CategoryModel
     */
    protected function getCategoryModel()
    {
        if (null == $this->categoryModel) {
            $this->categoryModel = $this->container->get('ccdn_forum_forum.model.category');
        }

        return $this->categoryModel;
    }

    /**
     *
     * @access protected
     * @return \CCDNForum\ForumBundle\Model\FrontModel\BoardModel
     */
    protected function getBoardModel()
    {
        if (null == $this->boardModel) {

Resources/views/User/Topic/Partial/stat_mods.html.twig
{%- spaceless -%}

	<section class="row clearfix">
		{%- if topic.isDeleted or topic.isClosed %}
	        <div class="alert alert-danger">
			    {%- if topic.isDeleted -%}
		            <i class="glyphicon glyphicon-trash"></i>

		            {{- 'topic.deleted-by' | trans({}, 'CCDNForumForumBundle') |raw -}}
					{{- topic.getDeletedBy -}}

					&nbsp;&#183;

		            {{- topic.getDeletedDate |date(ccdn_forum_forum.topic.user.show.deleted_datetime_format) -}}
			    {%- endif -%}

			    {%- if topic.isClosed -%}
					{%- if topic.isDeleted -%}<br>{%- endif -%}
		            <i class="glyphicon glyphicon-lock"></i>

		            {{- 'topic.closed-by' | trans({}, 'CCDNForumForumBundle') |raw -}}
					{{- topic.getClosedBy -}}

					&nbsp;&#183;

		            {{- topic.getClosedDate |date(ccdn_forum_forum.topic.user.show.closed_datetime_format) -}}
			    {%- endif -%}
	        </div>
		{%- endif -%}

	    {%- if topic.isSticky -%}
	        <div class="alert alert-info">
		        <i class="glyphicon glyphicon-bullhorn"></i>

	            {{- 'topic.stickied-by' | trans({}, 'CCDNForumForumBundle') |raw -}}
				{{- topic.stickiedBy -}}

				&nbsp;&#183;

	            {{- topic.getStickiedDate |date(ccdn_forum_forum.topic.user.show.deleted_datetime_format) -}}
	        </div>
	    {%- endif -%}
	</section>

{%- endspaceless -%}

Resources/views/User/Topic/Partial/stat_vitals.html.twig
{%- spaceless -%}

	<header class="row clearfix">
		<div class="col-md-6">
		    <span class="lead" title="{{- topic.getTitle -}}">{{- topic.getTitle |capitalize -}}</span>
		</div>
		<div class="col-md-6 text-right">
		    <span class="label label-default" title="{{- topic.cachedReplyCount -}}">
				{{- 'topic.reply-count-label' |trans({}, 'CCDNForumForumBundle') -}}
				{{- topic.cachedReplyCount -}}
			</span>

			&nbsp;

			<span class="label label-default" title="{{- topic.cachedViewCount -}}">
				{{- 'topic.view-count-label' |trans({}, 'CCDNForumForumBundle') -}}
				{{- topic.cachedViewCount -}}
			</span>

		    {%- if subscription_count is defined -%}
				&nbsp;
		        <span class="label label-default" title="{{- subscription_count -}}">
					{{- 'topic.subscription-count-label' |trans({}, 'CCDNForumForumBundle') -}}
					{{- subscription_count -}}
				</span>
		    {%- endif -%}
		</div>
	</header>

{%- endspaceless -%}

Resources/views/User/Topic/Partial/topic_actions.html.twig
{%- spaceless -%}

	{%- if topic is defined -%}

		{%- if board is not defined -%}
			{%- set board = topic.getBoard -%}
		{%- endif -%}


		{%- if canReplyToTopic(topic, forum) -%}
		    <a class="btn btn-danger" rel="nofollow"
			 href="{{- path('ccdn_forum_user_topic_reply', {'forumName': forumName, 'topicId': topic.getId }) -}}">
				<i class="glyphicon glyphicon-comment"></i>
				{{- 'link.topic.reply' | trans({}, 'CCDNForumForumBundle') -}}
			</a>
		{%- else -%}
		    <a class="btn btn-danger disabled" rel="nofollow"
			 href="{{- path('ccdn_forum_user_topic_reply', {'forumName': forumName, 'topicId': topic.getId }) -}}">
				<i class="glyphicon glyphicon-lock"></i>
				{{- 'link.topic.reply' | trans({}, 'CCDNForumForumBundle') -}}
			</a>
		{%- endif -%}


		{%- if canSubscribeToTopic(topic, forum, (subscription is defined ? subscription : null)) -%}
			<a class="btn btn-info" href="{{- path('ccdn_forum_user_subscription_subscribe', {'forumName': forumName, 'topicId': topic.getId }) -}}">
				<i class="glyphicon glyphicon-eye-open"></i>
				{{- 'link.topic.subscribe' | trans({}, 'CCDNForumForumBundle') -}}
			</a>
		{%- endif -%}

		{%- if canUnsubscribeFromTopic(topic, forum, (subscription is defined ? subscription : null)) -%}
			<a class="btn btn-info" href="{{- path('ccdn_forum_user_subscription_unsubscribe', {'forumName': forumName, 'topicId': topic.getId }) -}}">
				<i class="glyphicon glyphicon-eye-close"></i>
				{{- 'link.topic.unsubscribe' | trans({}, 'CCDNForumForumBundle') -}}
			</a>
		{%- endif -%}


		{%- if is_granted('ROLE_MODERATOR') -%}
			<div class="btn-group">
				<a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#">
					<i class="glyphicon glyphicon-wrench"></i>
					{{- 'link.admin.index' |trans({}, 'CCDNForumForumBundle') -}}
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">

					{%- if canStickyTopic(topic, forum) -%}
						<li>
							<a href="{{- path('ccdn_forum_moderator_topic_sticky', {'forumName': forumName, 'topicId': topic.getId }) -}}">
								<i class="glyphicon glyphicon-bullhorn"></i>
								{{- 'link.topic.sticky' |trans({}, 'CCDNForumForumBundle') -}}
							</a>
						</li>
					{%- endif -%}

					{%- if canUnstickyTopic(topic, forum) -%}
						<li>
							<a href="{{- path('ccdn_forum_moderator_topic_unsticky', {'forumName': forumName, 'topicId': topic.getId }) -}}">
								<i class="glyphicon glyphicon-bullhorn"></i>
								{{- 'link.topic.unsticky' |trans({}, 'CCDNForumForumBundle') -}}
							</a>
						</li>
					{%- endif -%}

					{%- if canCloseTopic(topic, forum) -%}
						<li>
							<a href="{{- path('ccdn_forum_moderator_topic_close', {'forumName': forumName, 'topicId': topic.getId }) -}}">
								<i class="glyphicon glyphicon-lock"></i>
								{{- 'link.topic.close' | trans({}, 'CCDNForumForumBundle') -}}
							</a>
						</li>
					{%- endif -%}

					{%- if canReopenTopic(topic, forum) -%}
						<li>
							<a href="{{- path('ccdn_forum_moderator_topic_reopen', {'forumName': forumName, 'topicId': topic.getId }) -}}">
								<i class="glyphicon glyphicon-lock"></i>
								{{- 'link.topic.reopen' | trans({}, 'CCDNForumForumBundle') -}}
							</a>
						</li>
					{%- endif -%}

					{%- if canRestoreTopic(topic, forum) -%}
						<li>
							<a href="{{- path('ccdn_forum_moderator_topic_restore', {'forumName': forumName, 'topicId': topic.getId }) -}}">
								<i class="glyphicon glyphicon-trash"></i>
								{{- 'link.topic.restore' |trans({}, 'CCDNForumForumBundle') -}}
							</a>
						</li>
					{%- endif -%}

					{%- if canDeleteTopic(topic, forum) -%}
						<li>
							<a href="{{- path('ccdn_forum_moderator_topic_delete', {'forumName': forumName, 'topicId': topic.getId }) -}}">
								<i class="glyphicon glyphicon-trash"></i>
								{{- 'link.topic.delete' |trans({}, 'CCDNForumForumBundle') -}}
							</a>
						</li>
					{%- endif -%}

					{%- if canTopicChangeBoard(topic, forum) -%}
						<li>
							<a href="{{- path('ccdn_forum_moderator_topic_change_board', {'forumName': forumName, 'topicId': topic.getId }) -}}">
								<i class="glyphicon glyphicon-move"></i>
								{{- 'link.topic.change_board' | trans({}, 'CCDNForumForumBundle') -}}
							</a>
						</li>
					{%- endif -%}

				</ul>
			</div>

		{%- endif -%}

	{%- endif -%}

{%- endspaceless -%}

Resources/views/User/Topic/Partial/transcript.html.twig
{%- spaceless -%}

	<div class="forum-topic-transcript">
		<h3>{{- 'topic.transcript' |trans({}, 'CCDNForumForumBundle') -}}</h3>

		<div class="well pre-scrollable">
			{%- for key, post in topic.getPosts -%}

				{%- if post.isDeleted == false or is_granted('ROLE_MODERATOR') -%}

					<div class="col-md-12">
						<article class="row panel panel-{%- if post.isDeleted == false or is_granted('ROLE_MODERATOR') -%} default {% else -%} danger {% endif -%}
						clearfix" data-snip="{{- post.getBody |slice(0,24) -}}" {%- if post.id %} id="post_{{- post.getId -}}"{% endif %}>

						    <header class="panel-heading">
								{%- if post.getCreatedBy -%}
							        {{- 'post.posted-by' |trans({}, 'CCDNForumForumBundle') |raw -}}
									{{- post.getCreatedBy.username -}}

							        &nbsp;&#183;

								{%- endif -%}

						        <span class="timestamper" title="{{- post.getCreatedDate |date('Y-m-d H:i:s T Z', 'Europe/London') -}}">
						            {{- post.getCreatedDate |date(ccdn_forum_forum.item_post.created_datetime_format) -}}
						        </span>
							</header>

							<div class="panel-body">
								<p>
									{{ post.getBody }}
								</p>
							</div>

						</article>
					</div>

				{%- endif -%}
			{%- endfor -%}
		</div>
	</div>

{%- endspaceless -%}